config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  root to: 'pages#home'

  resources :posts
  resources :videos
  resources :portraits
  resources :likes, only: :create

  get '/about', to: 'pages#about'
  get '/search', to: 'pages#search'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount Attachinary::Engine => "/attachinary"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :likeable, polymorphic: true
  validates :ip, uniqueness: { scope: :likeable,
    message: "You already liked this post" }
end

app/models/portrait.rb
class Portrait < ApplicationRecord
  belongs_to :user
  has_attachment :photo
  # searchkick
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :likes, as: :likeable
  belongs_to :category
  belongs_to :user
  searchkick

  include Bootsy::Container
  has_attachment :card_photo

  validates :title, presence: true, length: { maximum: 100 }
  validates :introduction, presence: true, length: { maximum: 300 }
  validates :content, presence: true
  validates :category, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :posts
  has_many :videos
  has_many :portraits



  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/video.rb
class Video < ApplicationRecord
  has_many :likes, as: :likeable
  belongs_to :category
  belongs_to :user
  searchkick


  include Bootsy::Container
  has_attachment :card_photo

  validates :title, presence: true, length: { maximum: 100 }
  validates :link, presence: true
  validates :content, presence: true
  validates :category, presence: true



  # def self.search_category(category)
  #   if search_category
  #     self.where("category like ?", "%#{search_category}%")
  #   else
  #     self.all
  #   end
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_categories
  before_action :latest_posts

  private

  def latest_posts
    @latest_posts = Post.all.order(created_at: :asc).first(5)
    @latest_videos = Video.all.order(created_at: :asc).first(5)
  end

  def set_categories
    @categories = Category.all.order(name: :asc)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @like = Like.create(like_params)
    redirect_to @like.likeable
  end

  private

  def like_params
    params.require(:like).permit(:ip, :likeable_type, :likeable_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @categories = Category.all.order(name: :asc)
    @posts = Post.all.order(created_at: :desc).first(4)
    @videos = Video.all.order(created_at: :desc).first(4)
    @banner_post = Post.all.order(created_at: :asc).first
  end

  def search
    if params[:category]

      @posts = Post.all.where(category: params[:category]).order(created_at: :desc)

      @videos = Video.all.where(category: params[:category]).order(created_at: :desc)


    else
      @posts = Post.search(params[:search])
      @videos = Video.search(params[:search])
    end

  end
end

app/controllers/portraits_controller.rb
class PortraitsController < ApplicationController
  before_action :get_portrait, only: [:show, :update, :edit, :destroy]
  def index
    @portraits = Portrait.all.order(created_at: :desc)
  end

  def new
    if user_signed_in? && current_user.admin?
      @portrait = Portrait.new
    else
      redirect_to root_path
    end
  end

  def create
    @portrait = Portrait.new(portrait_params)
    @portrait.user = current_user
    if @portrait.save
      redirect_to portraits_path
    else
      render :new
    end
  end

  def edit
    if user_signed_in? && current_user.admin?

    else
      redirect_to root_path
    end
  end

  def update
    @portrait.update(portrait_params)
    if @portrait.save
      redirect_to portraits_path
    else
      render :edit
    end
  end

  def destroy
    if @portrait.destroy
      redirect_to portraits_path
    else
      render :edit
    end
  end

  private

  def get_portrait
    @portrait = Portrait.find(params[:id])
  end

  def portrait_params
    params.require(:portrait).permit(:photo, :description)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :get_post, only: [:show, :update, :edit, :destroy, :add_like]

  def index
    if params[:post] && params[:post] == 'recent'
      @title = 'RECENT POSTS'
      @posts = Post.all.order(created_at: :desc)
    elsif params[:post] && params[:post] == 'top'
      @title = 'TOP RATED POSTS'
      @posts = Post.includes(:likes).order("likes.created_at asc")
    else
      @title = 'RECENT POSTS'
      @posts = Post.all.order(created_at: :desc)
    end
  end

  def show
    @like = @post.likes.build(ip: request.remote_ip)
    @likes_counter = @post.likes.all.count
    @can_like = @like.valid?
  end

  def new
    if user_signed_in? && current_user.admin?
      @post = Post.new
    else
      redirect_to root_path
    end
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def edit
    if user_signed_in? && current_user.admin?
      @categories = Category.all
    else
      redirect_to root_path
    end
  end

  def update
    @post.update(post_params)
    if @post.save
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    if user_signed_in? && current_user.admin?
      if @post.destroy
        redirect_to posts_path
      else
        render :edit
      end
    else
      redirect_to root_path
    end
  end

  private

  def get_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :introduction, :category_id, :content, :bootsy_image_gallery_id, :card_photo)
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :get_video, only: [:show, :update, :edit, :destroy]
  def index
    @videos = Video.all.order(created_at: :asc)
  end

  def show
    @video_id = @video.link.split("=").last
    @video_link = ("https://www.youtube.com/embed/" + @video_id).to_s
    @like = @video.likes.build(ip: request.remote_ip)

    @likes_counter = @video.likes.all.count
    @can_like = @like.valid?
  end

  def new
    if user_signed_in? && current_user.admin?
      @video = Video.new
    else
      redirect_to root_path
    end
  end

  def create
    @video = Video.new(video_params)
    @video.user = current_user
    if @video.save
      redirect_to video_path(@video)
    else
      render :new
    end
  end

  def edit
    if user_signed_in? && current_user.admin?
      @categories = Category.all
    else
      redirect_to root_path
    end
  end

  def update
    @video.update(video_params)
    if @video.save
      redirect_to videos_path
    else
      render :edit
    end
  end

  def destroy
    if @video.destroy
      redirect_to videos_path
    else
      render :edit
    end
  end

  private

  def get_video
    @video = Video.find(params[:id])
  end

  def video_params
    params.require(:video).permit(:title, :link, :introduction, :category_id, :content, :bootsy_image_gallery_id, :card_photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/portraits_helper.rb
module PortraitsHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <link rel="icon" href="<%= image_path "logo-black.png" %>">

  <meta property="og:url"                content="<%= (yield(:url) || request.original_url).squish %>" />
  <meta property="og:title"              content="<%= (yield(:title) || "Elephant & Castle").squish %>" />
  <meta property="og:description"        content="<%= (yield(:introduction) || "Elephant & Castle").squish %>" />
  <meta property="og:image"              content="<%= (yield(:image) || "").squish %>"/>

  <title>Elephant &amp; Castle</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
</head>
<body>
  <%= render 'shared/navbar', categories: @categories %>
  <%= yield %>
  <%= render 'shared/footer' %>

  <%= javascript_include_tag 'application' %>
  <%= cloudinary_js_config %> <!-- Append this after the main `javascript_include_tag`. -->

</body>
</html>

app/views/likes/_add-like.html.erb
<div class="text-center">
  <%= form_for(@like) do |f| %>
  <%= f.hidden_field :ip %>
  <%= f.hidden_field :likeable_type %>
  <%= f.hidden_field :likeable_id %>
  <button type="submit" class="btn btn-success">
    <i class="fa fa-thumbs-up fa-fw" aria-hidden="true"></i> Like
  </button>
  <% end %>
</div>

app/views/pages/about.html.erb
<div class="container">
  <div class="banner">
    <%= render "shared/banner-title" %>
    <div class="banner-image" style="background-image: url(<%= image_path 'about_banner.jpg' %>);">
      <div class="banner-header">
        <h3>ABOUT ME</h3>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-12 col-md-8">
      <div class="banner-title"><h2>ADRIANA</h2></div>
      <div class="row">

      </div>
    </div>
    <div class="col-xs-12 col-md-4">
     <%= render "shared/sidebar", posts: @latest_posts, videos: @latest_videos %>
   </div>
 </div>
 <%= render "shared/map" %>
</div>

<% content_for(:introduction) do %>
"Elephant & Castle"
<% end %>

<% content_for(:title) do %>
"Elephant & Castle"
<% end %>

<% content_for(:url) do %>
<%= request.original_url %>
<% end %>

<% content_for(:image) do %>
<%= image_path "about_banner.jpg" %>
<% end %>

app/views/pages/home.html.erb
<div class="container-fluid not-padded">

  <div class="banner">
    <div class="banner-image" style="background-image: url(<%= cl_image_path @banner_post.card_photo.path %>);">

      <div class="banner-category">
        <p><%= @banner_post.category.name.upcase %></p>
      </div>
      <div class="banner-header">
        <h3><%= @banner_post.title.upcase %></h3>
      </div>
      <div class="banner-action">
        <%= link_to "READ MORE", post_path(@banner_post) %>
      </div>
    </div>
  </div>
  <%= render "shared/banner-title" %>
</div>
<div class="container">
<div class="promo-cards hidden-xs">
    <% @categories.each do |category| %>
    <div class="promo-card" style="background-image: url(<%= category.image_link %>);">
      <div class="promo-card-border">
        <div class="promo-card-title">
          <h4><%= category.name %></h4>
        </div>
      </div>
      <%= link_to "", search_path(category: category), class: "promo-card-link" %>
    </div>
    <% end %>
  </div>
  <div class="row">
    <div class="col-xs-12 col-md-8">
      <div class="banner-title"><h2>RECENT POSTS</h2></div>
      <div class="row">
        <% @posts.each do |post| %>
        <div class="col-xs-12 col-md-6">
          <div class="post-index-card">
            <div class="post-index-card-image" style="background-image: url(<%= cl_image_path post.card_photo.path %>);">

            </div>
            <div class="post-index-card-category">
              <p><%= post.category.name.upcase %></p>
            </div>
            <div class="post-index-card-text">
              <h4><%= post.title %></h4>
              <p><%= post.introduction %></p>
            </div>
            <div class="post-index-card-date">
              <p>By <strong><%= post.user.name %></strong></p>
              <p><i class="fa fa-thumbs-up fa-fw" aria-hidden="true"></i> <%= post.likes.all.count %></p>
              <p><%= post.created_at.strftime('%b %d, %Y') %></p>
            </div>
            <%= link_to "", post_path(post), class: "post-index-card-link" %>
          </div>
        </div>
        <% end %>
      </div>


      <div class="banner-title"><h2>RECENT VIDEOS</h2></div>
      <div class="row">
        <% @videos.each do |video| %>
        <div class="col-xs-12 col-md-6">
          <div class="post-index-card">
            <div class="post-index-card-image" style="background-image: url(<%= cl_image_path video.card_photo.path %>);">

            </div>
            <div class="post-index-card-category">
              <p><%= video.category.name.upcase %></p>
            </div>
            <div class="post-index-card-text">
              <h4><%= video.title %></h4>
              <p><%= video.introduction %></p>
            </div>
            <div class="post-index-card-date">
              <p>By <strong><%= video.user.name %></strong></p>
              <p><i class="fa fa-thumbs-up fa-fw" aria-hidden="true"></i> <%= video.likes.all.count %></p>
              <p><%= video.created_at.strftime('%b %d, %Y') %></p>
            </div>
            <%= link_to "", video_path(video), class: "post-index-card-link" %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
    <div class="col-xs-12 col-md-4">
      <%= render "shared/sidebar", posts: @latest_posts, videos: @latest_videos %>
    </div>
  </div>
  <%= render "shared/map" %>
</div>

<% content_for(:introduction) do %>
"Elephant & Castle"
<% end %>

<% content_for(:title) do %>
"Elephant & Castle"
<% end %>

<% content_for(:url) do %>
<%= request.original_url %>
<% end %>

<% content_for(:image) do %>
<%= image_path "about_banner.jpg" %>
<% end %>

app/views/portraits/edit.html.erb
<div class="container full-screen">
  <h1>Edit portrait</h1>
  <%= simple_form_for @portrait do |f| %>
  <%= f.input :photo, as: :attachinary %>
  <%= f.input :description %>
  <%= f.button :submit, class: "btn btn-primary" %>
  <%= link_to "Cancel", portraits_path, class: "btn btn-default" %>
  <%= link_to "Delete", portrait_path(@portrait), method: :delete, class: "btn btn-danger", data: {confirm: 'Are you sure?'} %>
  <% end %>
</div>

app/views/portraits/index.html.erb
<div class="container full-screen">
  <%= render "shared/banner-title" %>
  <div class="row">
    <div class="col-xs-12 col-md-8">
      <div class="banner-title"><h3>RECENT PHOTOS</h3></div>
      <div class="row">
        <% @portraits.each do |portrait| %>
        <div class="col-xs-12 col-md-6">
          <div class="post-index-card">
            <div class="post-index-card-image" style="background-image: url(<%= cl_image_path portrait.photo.path %>);">

            </div>

            <div class="post-index-card-date">
              <p>By <strong><%= portrait.user.name %></strong></p>
              <% if user_signed_in? && current_user.admin? %>
              <%= link_to "Edit", edit_portrait_path(portrait), class: "post-index-card-link-edit" %>
              <% end %>
              <p><%= portrait.created_at.strftime('%b %d, %Y') %></p>
            </div>
            <div class="post-index-card-text">
              <p><%= portrait.description %></p>
            </div>
            <a href="<%= cl_image_path portrait.photo.path %>" data-lightbox="image-1" data-title="<%= portrait.description %>" class="post-index-card-link"></a>
          </div>
        </div>
        <% end %>
        <% if user_signed_in? && current_user.admin? %>
        <%= link_to "New portrait", new_portrait_path, class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
    <div class="col-xs-12 col-md-4">
     <%= render "shared/sidebar", posts: @latest_posts, videos: @latest_videos %>
   </div>
 </div>

</div>

<% content_for(:introduction) do %>
  "Portraits"
<% end %>

<% content_for(:title) do %>
  <%= @portraits.first.description %>
<% end %>

<% content_for(:url) do %>
  <%= request.original_url %>
<% end %>

<% content_for(:image) do %>
  <%= cl_image_path @portraits.first.photo.path %>
<% end %>

app/views/portraits/new.html.erb
<div class="container full-screen">
  <h1>New portrait</h1>
  <%= simple_form_for @portrait do |f| %>
  <%= f.input :photo, as: :attachinary, required: true %>
  <%= f.input :description, required: true %>
  <%= f.button :submit, class: "btn btn-primary" %>
  <%= link_to "Cancel", portraits_path, class: "btn btn-default" %>
  <% end %>
</div>

app/views/posts/edit.html.erb
<div class="container full-screen">
  <h1>Edit post</h1>
  <%= simple_form_for @post do |f| %>
  <%= f.input :card_photo, as: :attachinary %>
  <%= f.input :title %>
  <%= f.input :category_id, collection: Category.all %>
  <%= f.input :introduction %>
  <%= f.bootsy_area :content %>
  <%= f.button :submit, class: "btn btn-primary" %>
  <%= link_to "Cancel", posts_path, class: "btn btn-default" %>
  <%= link_to "Delete", post_path(@post), method: :delete, class: "btn btn-danger", data: {confirm: 'Are you sure?'} %>
  <% end %>
</div>

app/views/posts/index.html.erb
<div class="container full-screen">
  <%= render "shared/banner-title" %>
  <div class="row">
    <div class="col-xs-12 col-md-8">
      <div class="banner-title"><h3><%= @title %></h3></div>
      <div class="row">
        <% @posts.each do |post| %>
        <div class="col-xs-12 col-md-6">
          <div class="post-index-card">
            <div class="post-index-card-image" style="background-image: url(<%= cl_image_path post.card_photo.path %>);">

            </div>
            <div class="post-index-card-category">
              <p><%= post.category.name %></p>
            </div>
            <div class="post-index-card-text">
              <h4><%= post.title %></h4>
              <p><%= post.introduction %></p>
            </div>
            <div class="post-index-card-date">
              <p>By <strong><%= post.user.name %></strong></p>
              <% if user_signed_in? && current_user.admin? %>
              <%= link_to "Edit", edit_post_path(post), class: "post-index-card-link-edit" %>
              <% end %>
              <p><i class="fa fa-thumbs-up fa-fw" aria-hidden="true"></i> <%= post.likes.all.count %></p>
              <p><%= post.created_at.strftime('%b %d, %Y') %></p>
            </div>
            <%= link_to "", post_path(post), class: "post-index-card-link" %>
          </div>
        </div>
        <% end %>
        <% if user_signed_in? && current_user.admin? %>
        <%= link_to "New post", new_post_path, class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>

    <div class="col-xs-12 col-md-4">
     <%= render "shared/sidebar", posts: @latest_posts, videos: @latest_videos %>
   </div>
 </div>

</div>

app/views/posts/show.html.erb
<div class="container full-screen">
  <%= render "shared/banner-title" %>
  <div class="row">
    <div class="col-xs-12 col-md-8">
      <div class="post-image" style="background-image: url(<%= cl_image_path @post.card_photo.path %>)">
        <div class="post-image-border">
        <div class="post-image-title">
          <h1><%= @post.title %></h1>
        </div>
      </div>
      </div>
      <div class="post-content">
        <%= @post.content.html_safe %>
      </div>
      <div class="post-description">
        <p>By <%= @post.user.name %></p>
        <p><%=  pluralize(@likes_counter, 'like', 'likes')%></p>
        <p><%= @post.created_at.strftime('%b %d, %Y') %></p>
      </div>
      <% if @can_like %>
      <%= render "likes/add-like" %>
      <% if user_signed_in? && current_user.admin? %>
      <%= link_to "Edit", edit_post_path(@post), class: "btn btn-warning" %>
      <% end %>
      <% end %>
    </div>
    <div class="col-xs-12 col-md-4">
      <%= render "shared/sidebar", posts: @latest_posts, videos: @latest_videos %>
    </div>
  </div>
</div>



<% content_for(:introduction) do %>
<%= @post.introduction %>
<% end %>

<% content_for(:title) do %>
<%= @post.title %>
<% end %>

<% content_for(:url) do %>
<%= request.original_url %>
<% end %>

<% content_for(:image) do %>
<%= cl_image_path @post.card_photo.path %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">

  <div class="navbar-wagon-left hidden-xs hidden-sm">
    <a href="/" class="navbar-wagon-brand">
      <%= image_tag "logo-white.png" %>
    </a>

    <%= link_to "About", about_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <p data-toggle="dropdown", class="dropdown-toggle navbar-wagon-link" id="navbar-wagon-menu">Posts <i class="fa fa-angle-down fa-fw"></i></p>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><%= link_to 'Recent posts', posts_path(post: 'recent') %></li>
          <li><%= link_to 'Top rated posts', posts_path(post: 'top') %></li>
        </ul>
      </div>
    </div>
    <%= link_to "Videos", videos_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Photos", portraits_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <div class="navbar-wagon-item">
      <div class="dropdown">
        <p data-toggle="dropdown", class="dropdown-toggle navbar-wagon-link" id="navbar-wagon-menu">Categories <i class="fa fa-angle-down fa-fw"></i></p>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <% categories.each do |category| %>
          <li><%= link_to category.name.capitalize, search_path(category: category) %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-left navbar-wagon-dropdown-menu">
        <li><%= link_to "Latest posts", posts_path %></li>
        <li><%= link_to "Videos", videos_path %></li>
        <li><%= link_to "Photos", portraits_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </div>
  </div>


  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <form class="navbar-wagon-search" action="/search" method="get">
      <input type="text" name="search" id="search" class="navbar-wagon-search-input" placeholder="Search">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>
  </div>
</div>

app/views/shared/_sidebar.html.erb
     <div class="sidebar-content-title">
      <h5>ABOUT ME</h5>
    </div>
    <%= image_tag "adriana.jpg", class: "sidebar-content-image img-thumbnail" %>
    <div class="sidebar-content-text">
      <p>Welcome to <strong>Elephant &amp; Castle</strong>, my name is Adriana and I love photography, travelling and... <%= link_to "[read more]", about_path %></p>
    </div>
    <ul class="list-inline sidebar-content-links">
      <li><a href="https://www.facebook.com/adriekswsk"><i class="fa fa-facebook-official fa-fw"></i></a></li>
      <li><a href="https://www.instagram.com/kosokiki/?hl=en"><i class="fa fa-instagram fa-fw"></i></a></li>
      <li><a href="https://www.youtube.com/channel/UC7-QSGYY7IO2o9t1nzvHuBg"><i class="fa fa-youtube fa-fw"></i></a></li>
    </ul>
    <div class="sidebar-content-title">
      <h5>LATEST POSTS</h5>
    </div>
    <% posts.each do |post| %>
    <div class="product">
      <%= cl_image_tag post.card_photo.path, class: "product-image hidden-xs" %>
      <div class='product-body'>
        <h3><%= post.title %></h3>
        <p><%= post.introduction[0..35] %>...</p>
      </div>
      <%= link_to "", post_path(post), class: "product-link" %>
    </div>
    <% end %>

    <div class="sidebar-content-title">
      <h5>LATEST VIDEOS</h5>
    </div>
    <% videos.each do |video| %>
    <div class="product">
      <%= cl_image_tag video.card_photo.path, class: "product-image hidden-xs" %>
      <div class='product-body'>
        <h3><%= video.title %></h3>
        <p><%= video.introduction[0..35] %>...</p>
      </div>
      <%= link_to "", video_path(video), class: "product-link" %>
    </div>
    <% end %>
    <div class="sidebar-content-title">
      <h5>EMAIL ME</h5>
    </div>
    <div class="sidebar-content-email form-group">
      <form method="POST" action="https://formspree.io/adriana.kosowski.bba@edhec.com">
        <input type="email" name="email" placeholder="Your email" class="form-control">
        <input type="subject" name="subject" placeholder="Subject" class="form-control">
        <textarea name="message" placeholder="Your message" class="form-control"></textarea>
        <button type="submit" class="btn btn-primary"><i class="fa fa-paper-plane fa-fw"></i>  Send</button>
      </form>
    </div>

app/views/videos/index.html.erb
<div class="container full-screen">
  <%= render "shared/banner-title" %>
  <div class="row">
    <div class="col-xs-12 col-md-8">
      <div class="banner-title"><h3>RECENT VIDEOS</h3></div>
      <div class="row">
        <% @videos.each do |video| %>
        <div class="col-xs-12 col-md-6">
          <div class="post-index-card">
            <div class="post-index-card-image" style="background-image: url(<%= cl_image_path video.card_photo.path %>);">
            </div>
            <div class="post-index-card-category">
              <p><%= video.category.name %></p>
            </div>
            <div class="post-index-card-text">
              <h4><%= video.title %></h4>
              <p><%= video.introduction %></p>
            </div>
            <div class="post-index-card-date">
              <p>By <strong><%= video.user.name %></strong></p>
              <% if user_signed_in? && current_user.admin? %>
              <%= link_to "Edit", edit_video_path(video), class: "post-index-card-link-edit" %>
              <% end %>
              <p><i class="fa fa-thumbs-up fa-fw" aria-hidden="true"></i> <%= video.likes.all.count %></p>
              <p><%= video.created_at.strftime('%b %d, %Y') %></p>
            </div>
            <%= link_to "", video_path(video), class: "post-index-card-link" %>
          </div>
        </div>
        <% end %>
        <% if user_signed_in? && current_user.admin? %>
        <%= link_to "New video", new_video_path, class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
    <div class="col-xs-12 col-md-4">
     <%= render "shared/sidebar", posts: @latest_posts, videos: @latest_videos %>
   </div>
 </div>
</div>

app/views/videos/show.html.erb
<div class="container full-screen">
  <%= render "shared/banner-title" %>
  <div class="row">
    <div class="col-xs-12 col-md-8">
      <div class="banner-title"><h3><%= @video.title.upcase %></h3></div>
      <iframe width="100%" height="415" src="<%= @video_link %>" frameborder="0" allowfullscreen></iframe>
      <div class="post-content">
        <%= @video.content.html_safe %>
      </div>
      <div class="post-description">
        <p>By <%= @video.user.name %></p>
        <p><%=  pluralize(@likes_counter, 'like', 'likes')%></p>
        <p><%= @video.created_at.strftime('%b %d, %Y') %></p>
      </div>
      <% if @can_like %>
      <%= render "likes/add-like" %>
      <% end %>
      <% if user_signed_in? && current_user.admin? %>
      <%= link_to "Edit", edit_video_path(@video), class: "btn btn-warning" %>
      <% end %>
    </div>
    <div class="col-xs-12 col-md-4">
      <%= render "shared/sidebar", posts: @latest_posts, videos: @latest_videos %>
    </div>
  </div>
</div>

<% content_for(:introduction) do %>
<%= @video.introduction %>
<% end %>

<% content_for(:title) do %>
<%= @video.title %>
<% end %>

<% content_for(:url) do %>
<%= request.original_url %>
<% end %>

<% content_for(:image) do %>
<%= cl_image_path @video.card_photo.path %>
<% end %>